project:
  type: website
  output-dir: docs

website:
  title: "R en acción Webscrapping con `{rvest}`"
  favicon: logo.png
  
  page-footer:
    left: "&copy; 2025 Ariana Bardauil"
    right: "Website construida con [Quarto](https://quarto.org/)."
    background: "#4dd0e1"
  
  sidebar:
    background: "#1f2430"
    logo: "logo.png"
    pinned: true
    align: center
    style: docked
    type: dark
    
    contents:
      - href: index.qmd
        text: ¿Qué necesitamos?
      - href: about.qmd
        text: Diapositivas
      - href: practica.qmd
        text: Práctica

format:
  html:
    theme: [flatly, styles.scss]
    toc: false

editor: visual

